# Generated by Django 4.0.3 on 2022-04-20 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_alter_ourrecord_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourrecord',
            name='shop',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ourrecord',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 11, 18, 20, 113129)),
        ),
    ]
