# Generated by Django 4.0.3 on 2022-04-21 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_ourrecord_shop_alter_ourrecord_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourrecord',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 21, 8, 52, 4, 966167)),
        ),
    ]
